  version: '3'
  services:
    db:
      image: postgres:latest
      container_name: db_container
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5433:5432"
      volumes:
        - ./init:/docker-entrypoint-initdb.d/

    web:
      build: .
      command: bash -c "./wait-for-it.sh db:5432 -- python portal_presas/manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - db
      environment:
        DATABASE_HOST: db
        DATABASE_NAME: ${POSTGRES_DB}
        DATABASE_USER: ${POSTGRES_USER}
        DATABASE_PASSWORD: ${POSTGRES_PASSWORD}

